site_name: EP_S3_Documentatiion
site_description: Documentation for S3 Service
site_dir: site
copyright: Copyright &copy; 2020, EP.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'

plugins:
  - search
  - mermaid2:
      arguments:
        sequence:
          showSequenceNumbers: 'true'
